name: linkcheck
version: 2.0.21 # Don't forget to update in lib/linkcheck.dart, too.

description: >-
  A very fast link-checker. Crawls sites and checks integrity of links
  both in HTML and in CSS.

homepage: https://github.com/filiph/linkcheck

environment:
  sdk: '>=2.11.99 <3.0.0'

dependencies:
  args: '>=1.5.1 <3.0.0'
  console: ^4.1.0
  csslib: ^0.17.0
  glob: ^2.0.1
  html: ^0.15.0
  logging: ^1.0.1
  path: ^1.6.2
  source_span: ^1.5.5
  stream_channel: ^2.0.0

dev_dependencies:
  dhttpd: ^4.0.0
  pedantic: ^1.7.0
  test: ^1.6.3
  cli_pkg: ^1.4.0
  grinder: ^0.9.0

executables:
  linkcheck: linkcheck
